# Generated by Django 4.1.10 on 2023-09-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPackageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameKg', models.CharField(max_length=100, verbose_name='Кыргызча аталышы')),
                ('nameEn', models.CharField(max_length=100, verbose_name='Package data name')),
                ('nameRu', models.CharField(max_length=100, verbose_name='Название')),
                ('height', models.FloatField(default=0, verbose_name='Высота')),
                ('weight', models.FloatField(default=0, verbose_name='Вес')),
                ('width', models.FloatField(default=0, verbose_name='Ширина')),
                ('order', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Информация о пакете',
                'verbose_name_plural': 'Информации о пакетах',
            },
        ),
        migrations.RemoveField(
            model_name='modelpackage',
            name='weight',
        ),
    ]
