# Generated by Django 4.1.10 on 2023-10-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_modelpackagedata_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpackage',
            name='height',
            field=models.FloatField(default=0, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='modelpackage',
            name='length',
            field=models.FloatField(default=0, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='modelpackage',
            name='width',
            field=models.FloatField(default=0, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='modelrequests',
            name='height',
            field=models.FloatField(default=0, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='modelrequests',
            name='length',
            field=models.FloatField(default=0, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='modelrequests',
            name='width',
            field=models.FloatField(default=0, verbose_name='Ширина'),
        ),
    ]
