# Generated by Django 4.1.10 on 2023-10-03 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_modelpackage_height_modelpackage_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrequests',
            name='packageData',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modelpackagedata', verbose_name='О посылке'),
        ),
    ]
