# Generated by Django 4.1.10 on 2023-10-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modelrequests_packagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpackagedata',
            name='icon',
            field=models.TextField(blank=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='modelpackagedata',
            name='infoEn',
            field=models.TextField(blank=True, verbose_name='Information'),
        ),
        migrations.AddField(
            model_name='modelpackagedata',
            name='infoKg',
            field=models.TextField(blank=True, verbose_name='Маалымат'),
        ),
        migrations.AddField(
            model_name='modelpackagedata',
            name='infoRu',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='modelpackagedata',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес'),
        ),
    ]
