# Generated by Django 4.1.10 on 2023-10-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modelpackagedata_icon_modelpackagedata_infoen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrequests',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Расходы'),
        ),
        migrations.AddField(
            model_name='modelrequests',
            name='receiverName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя получателя'),
        ),
        migrations.AddField(
            model_name='modelrequests',
            name='receiverPhone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя номер получателя'),
        ),
        migrations.AddField(
            model_name='modelrequests',
            name='senderName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя отправителя'),
        ),
        migrations.AddField(
            model_name='modelrequests',
            name='senderPhone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон номер отправителя'),
        ),
        migrations.AddField(
            model_name='modelrequests',
            name='serviceName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наименование услуги'),
        ),
    ]
