# Generated by Django 4.1.10 on 2023-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modelrequests_cost_modelrequests_receivername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpackage',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес'),
        ),
    ]
