# Generated by Django 4.1.10 on 2023-10-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_client_addresses'),
        ('category', '0004_modeladdress'),
        ('core', '0009_modelpackage_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('depot', 'Склад'), ('custom', 'Custom')], default='depot', max_length=20, verbose_name='Тип')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Телефон')),
                ('receiverName', models.CharField(blank=True, max_length=200, verbose_name='Имя получателя')),
                ('nameAddress', models.CharField(blank=True, max_length=255, verbose_name='Название адреса')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.modelcity', verbose_name='Город')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.modelcountry', verbose_name='Страна')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modeldepots', verbose_name='Склад')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
