# Generated by Django 4.1.10 on 2023-10-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_modeladdresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Фото')),
                ('order', models.FloatField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Баннер для покупателя',
                'verbose_name_plural': 'Баннеры для покупателей',
            },
        ),
    ]
