# Generated by Django 4.1.10 on 2023-10-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_buyeruser_countries_buyeruser_websites'),
        ('core', '0011_buyerbanners'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBuyerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, verbose_name='Ссылка')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон номер')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('confirmed', 'Подтверждено'), ('in_progress', 'В процессе'), ('bought', 'Куплено'), ('sent', 'Отправлено')], default='created', max_length=50, verbose_name='Статус')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка покупателя',
                'verbose_name_plural': 'Заявки покупателей',
            },
        ),
    ]
