# Generated by Django 4.1.10 on 2023-10-26 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_user_type_store'),
        ('core', '0013_modelitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField(default=0, verbose_name='ID Магазина')),
                ('totalCost', models.IntegerField(default=0, verbose_name='Общая сумма')),
                ('user', models.CharField(blank=True, max_length=200, null=True, verbose_name='Пользователь')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адресс')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон номер')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарии')),
                ('storeName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название магазина')),
                ('storeLogo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Лого магазина')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('packing', 'Упаковывается'), ('delivering', 'В пути'), ('delivered', 'Доставлено'), ('rejected', 'Отказано'), ('client_reject', 'Отменен')], default='new', max_length=50, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('isoptovik', models.BooleanField(default=False, verbose_name='Оптовик?')),
                ('bonus', models.FloatField(default=0, verbose_name='Бонус')),
                ('pay_status', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.client', verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modelitem', verbose_name='Товар')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modelorder')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
