# Generated by Django 4.1.10 on 2023-10-28 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_subcategory_category'),
        ('core', '0014_modelorder_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelitem',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.modelcity', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='modelitem',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.modelcountry', verbose_name='Страна'),
        ),
    ]
