# Generated by Django 4.1.10 on 2023-10-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_modelitem_city_modelitem_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelorder',
            old_name='user_id',
            new_name='client',
        ),
        migrations.AddField(
            model_name='modelorder',
            name='addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modeladdresses', verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='modelorder',
            name='totalCost',
            field=models.FloatField(default=0, verbose_name='Общая сумма'),
        ),
    ]
