# Generated by Django 4.1.10 on 2023-10-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_user_id_modelorder_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelorder',
            name='address',
        ),
    ]
