# Generated by Django 4.1.10 on 2023-11-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_modelorder_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldepots',
            name='infoEn',
            field=models.TextField(blank=True, verbose_name='Information'),
        ),
        migrations.AddField(
            model_name='modeldepots',
            name='infoKg',
            field=models.TextField(blank=True, verbose_name='Маалымат'),
        ),
        migrations.AddField(
            model_name='modeldepots',
            name='infoRu',
            field=models.TextField(blank=True, verbose_name='Информация на русском'),
        ),
    ]
