# Generated by Django 4.1.10 on 2023-11-13 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_buyeruser_passport_back_buyeruser_passport_front_and_more'),
        ('core', '0020_modelvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelItemSearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон номер')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.TextField(blank=True, verbose_name='Фото')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Запрос на поиск товара',
                'verbose_name_plural': 'Запросы на поиск товара',
            },
        ),
    ]
