# Generated by Django 4.1.10 on 2023-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_modelextraservice'),
        ('core', '0021_modelitemsearchrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldepots',
            name='extraServices',
            field=models.ManyToManyField(blank=True, to='category.modelextraservice', verbose_name='Экстра сервисы'),
        ),
    ]
