# Generated by Django 4.1.10 on 2023-11-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_modeldepots_extraservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldepots',
            name='isCommercial',
            field=models.BooleanField(default=False, verbose_name='Коммерческий'),
        ),
    ]
