# Generated by Django 4.1.10 on 2023-11-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_modelextraservice'),
        ('core', '0023_modeldepots_iscommercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrequests',
            name='extraServices',
            field=models.ManyToManyField(blank=True, to='category.modelextraservice', verbose_name='Экстра сервисы'),
        ),
    ]
