# Generated by Django 4.1.10 on 2023-12-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_alter_category_icon'),
        ('core', '0024_modelrequests_extraservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.TextField(blank=True, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Нужный товар',
                'verbose_name_plural': 'Нужные товары',
            },
        ),
        migrations.RemoveField(
            model_name='modelitemsearchrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='modelitemsearchrequest',
            name='photo',
        ),
        migrations.AddField(
            model_name='modelalaket',
            name='flyTime',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Время вылета'),
        ),
        migrations.AddField(
            model_name='modelpackage',
            name='extraServices',
            field=models.ManyToManyField(blank=True, to='category.modelextraservice', verbose_name='Экстра сервис'),
        ),
        migrations.AddField(
            model_name='modelitemsearchrequest',
            name='wantedItems',
            field=models.ManyToManyField(blank=True, to='core.wanteditems', verbose_name='Товары поиска'),
        ),
    ]
