# Generated by Django 4.1.10 on 2023-12-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_wanteditems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, verbose_name='Ссылка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Карзина запросов',
                'verbose_name_plural': 'Карзины запросов',
            },
        ),
        migrations.AddField(
            model_name='modelbuyerrequest',
            name='cart_request',
            field=models.ManyToManyField(blank=True, to='core.cartrequest', verbose_name='Корзина запросов'),
        ),
    ]
