# Generated by Django 4.1.10 on 2023-12-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_modeldepots_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='order',
        ),
        migrations.AddField(
            model_name='modelorder',
            name='items',
            field=models.ManyToManyField(blank=True, to='core.cartitems', verbose_name='Карзина'),
        ),
    ]
