# Generated by Django 4.1.10 on 2024-01-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_cartitems_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbuyerrequest',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
        migrations.AddField(
            model_name='modelitemsearchrequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
