# Generated by Django 4.1.10 on 2024-01-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_modelbuyerrequest_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrequests',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
    ]
