# Generated by Django 4.1.10 on 2024-01-06 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_modelrequests_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrequests',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modeladdresses', verbose_name='Адрес'),
        ),
    ]
