# Generated by Django 4.1.10 on 2024-01-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_modeldepots_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldepots',
            name='cityStr',
            field=models.TextField(blank=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='modeldepots',
            name='instructionsEn',
            field=models.TextField(blank=True, verbose_name='Instructions'),
        ),
        migrations.AddField(
            model_name='modeldepots',
            name='instructionsKg',
            field=models.TextField(blank=True, verbose_name='Корсотмолор'),
        ),
        migrations.AddField(
            model_name='modeldepots',
            name='instructionsRu',
            field=models.TextField(blank=True, verbose_name='Инструкция'),
        ),
        migrations.AddField(
            model_name='modeldepots',
            name='link_zip',
            field=models.TextField(blank=True, verbose_name='Ccылка на ZIP'),
        ),
    ]
