# Generated by Django 4.1.10 on 2024-01-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_modeldepots_citystr_modeldepots_instructionsen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldepots',
            name='nameStart',
            field=models.BooleanField(default=False, verbose_name='Name start'),
        ),
        migrations.AddField(
            model_name='modeldepots',
            name='nameStr',
            field=models.TextField(blank=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='modeldepots',
            name='stateStr',
            field=models.TextField(blank=True, verbose_name='State str'),
        ),
    ]
