# Generated by Django 4.1.10 on 2024-01-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_modeldepots_namestart_modeldepots_namestr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldepots',
            name='surnameStr',
            field=models.CharField(blank=True, max_length=250, verbose_name='Surname'),
        ),
    ]
