# Generated by Django 4.1.10 on 2024-01-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_modeldepots_surnamestr'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldepots',
            name='email',
            field=models.CharField(blank=True, max_length=250, verbose_name='Email'),
        ),
    ]
