# Generated by Django 4.1.10 on 2024-01-25 04:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_modelcolor_modelmemory'),
        ('core', '0037_modeldepots_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelitem',
            name='colors',
            field=models.ManyToManyField(blank=True, to='category.modelcolor', verbose_name='Цвета'),
        ),
        migrations.AddField(
            model_name='modelitem',
            name='gender',
            field=models.TextField(blank=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='modelitem',
            name='memory',
            field=models.ManyToManyField(blank=True, to='category.modelmemory', verbose_name='Память'),
        ),
        migrations.AddField(
            model_name='modelitem',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Размеры'),
        ),
    ]
