# Generated by Django 4.1.10 on 2024-01-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_modelitem_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelitem',
            name='gender_type',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('kids', 'Детский')], default='male', max_length=30, verbose_name='Пол'),
        ),
    ]
