# Generated by Django 4.1.10 on 2024-01-25 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_modelcolor_modelmemory'),
        ('core', '0040_modelitem_gender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.modelcolor', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.modelmemory', verbose_name='Память'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='size',
            field=models.TextField(blank=True, null=True, verbose_name='Размер'),
        ),
    ]
