# Generated by Django 4.1.10 on 2024-02-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_modelitem_deschtml'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbuyerrequest',
            name='info',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='modelbuyerrequest',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='modelbuyerrequest',
            name='totalCost',
            field=models.FloatField(default=0, verbose_name='Стоимость'),
        ),
    ]
