# Generated by Django 4.1.13 on 2024-08-12 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0020_modelmatrix_alter_modelmemory_ram_and_more'),
        ('core', '0044_modelbuyerrequest_info_modelbuyerrequest_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelitem',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.modelmatrix', verbose_name='Screen ID'),
        ),
        migrations.AlterField(
            model_name='modelitem',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('kids', 'Детский'), ('any', 'Для всех')], default='male', max_length=30, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='modelitem',
            name='gender_type',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('kids', 'Детский'), ('any', 'Для всех')], default='male', max_length=30, verbose_name='Пол'),
        ),
    ]
