# Generated by Django 4.1.13 on 2024-08-13 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0020_modelmatrix_alter_modelmemory_ram_and_more"),
        ("core", "0045_modelitem_screen_alter_modelitem_gender_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelColorSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=50, verbose_name="Размер")),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_sizes",
                        to="category.modelcolor",
                        verbose_name="размер цвета",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_sizes",
                        to="core.modelitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет и Размер",
                "verbose_name_plural": "Цвета и Размеры",
            },
        ),
    ]
