# Generated by Django 4.1.13 on 2024-08-16 12:21

import category.imggenerate
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0020_modelmatrix_alter_modelmemory_ram_and_more'),
        ('core', '0046_modelcolorsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcolorsize',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_sizes', to='category.modelcolor', verbose_name='Hазмер цвета'),
        ),
        migrations.AlterField(
            model_name='modelitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=category.imggenerate.all_image_file_path, verbose_name='Фото'),
        ),
    ]
