# Generated by Django 4.1.13 on 2024-08-22 03:09

import category.imggenerate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_modelcolorsize_color_alter_modelitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelimage',
            name='image',
            field=models.FileField(upload_to=category.imggenerate.all_image_file_path, verbose_name='Фото'),
        ),
    ]
