# Generated by Django 4.1.13 on 2024-08-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_modelimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelitem',
            options={'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
