# Generated by Django 4.1.13 on 2024-09-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_modelpackage_delivery_type_modelpackage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelpackage",
            name="personal",
            field=models.BooleanField(default=False, verbose_name="Личная вещь"),
        ),
    ]
