# Generated by Django 4.1.13 on 2024-09-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_modelpackage_item_modelpackage_personal_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelrequests",
            name="package",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request",
                to="core.modelpackage",
            ),
        ),
    ]
