# Generated by Django 4.1.13 on 2024-09-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_modelrequests_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelpackage",
            name="customExpenses",
            field=models.FloatField(default=0, verbose_name="Таможенные расходы"),
        ),
    ]
