# Generated by Django 4.1.13 on 2024-09-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_modelpackage_customexpenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelpackage",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создан"),
                    ("RECEIVED_AT_WAREHOUSE", "Получен на складе"),
                    ("SENT", "Отправлен"),
                    ("ON_WAY", "В пути"),
                    ("ARRIVED_TRANSIT_COUNTRY", "Прибыл в транзитную страну"),
                    ("SENT_TO_DESTINATION_COUNTRY", "Отправлен в страну назначения"),
                    ("ON_WAY_TO_DESTINATION", "В пути"),
                    ("ARRIVED_DESTINATION_COUNTRY", "Прибыл в страну назначения"),
                    ("CUSTOMS_CLEARANCE", "Проходит таможенное оформление"),
                    (
                        "RECEIVED_AT_DESTINATION_WAREHOUSE",
                        "Получен на складе страны назначения",
                    ),
                    ("CDEK", "Посылка пришла в СДЭК"),
                    ("DELIVERED_TO_RECIPIENT", "Отправлен адресату"),
                ],
                default="CREATED",
                max_length=100,
                verbose_name="Статус",
            ),
        ),
    ]
