# Generated by Django 4.1.13 on 2024-09-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_confirmemailmodel"),
        ("core", "0056_alter_modelpackage_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("parcel", "Оплата за посылку"),
                            ("wallet", "Пополнение кошелька"),
                            ("store", "Оплата за товар в магазине"),
                        ],
                        max_length=10,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("paid", "Оплачено"), ("unpaid", "Не оплачено")],
                        default="unpaid",
                        max_length=10,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(max_length=255, verbose_name="Хеш транзакции"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_pay",
                        to="user.client",
                    ),
                ),
                (
                    "package",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crypto_pay",
                        to="core.modelpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата криптой",
            },
        ),
    ]
