# Generated by Django 4.1.13 on 2024-09-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_cryptopay"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cryptopay",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Оплата криптой",
                "verbose_name_plural": "Оплаты криптой",
            },
        ),
    ]
