# Generated by Django 4.1.13 on 2024-09-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_confirmemailmodel"),
        ("core", "0058_alter_cryptopay_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptopay",
            name="receipt_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Email для квитанции",
            ),
        ),
        migrations.AddField(
            model_name="cryptopay",
            name="send_receipt",
            field=models.BooleanField(
                default=False, verbose_name="Отправлять квитанцию?"
            ),
        ),
        migrations.AlterField(
            model_name="cryptopay",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crypto_pay",
                to="user.client",
            ),
        ),
    ]
