# Generated by Django 4.1.13 on 2024-09-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_cryptopay_receipt_email_cryptopay_send_receipt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelbuyerrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создано"),
                    ("confirmed", "Подтверждено"),
                    ("in_progress", "В процессе"),
                    ("bought", "Куплено"),
                    ("sent", "Отправлено"),
                ],
                default="CREATED",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
