# Generated by Django 4.2.7 on 2024-09-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_alter_modelbuyerrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptopay",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Оплачено"),
        ),
    ]
