# Generated by Django 4.2.7 on 2024-09-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_cryptopay_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptopay",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("parcel", "Оплата за посылку"),
                    ("wallet", "Пополнение кошелька"),
                    ("store", "Оплата за товар в магазине"),
                    ("item", "Заявка на покупку товара"),
                ],
                max_length=10,
                verbose_name="Тип оплаты",
            ),
        ),
        migrations.CreateModel(
            name="TariffSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=1, max_digits=10, verbose_name="Вес в кг."
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "depot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariff",
                        to="core.modeldepots",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тарифная сетка",
                "verbose_name_plural": "Тарифные сетки",
            },
        ),
    ]
