# Generated by Django 4.2.7 on 2024-09-24 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_alter_cryptopay_payment_type_tariffschedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tariffschedule",
            name="price",
        ),
        migrations.RemoveField(
            model_name="tariffschedule",
            name="weight",
        ),
        migrations.AddField(
            model_name="modelbuyerrequest",
            name="trackNumbers",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Номер дорожки"
            ),
        ),
        migrations.AlterField(
            model_name="tariffschedule",
            name="depot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tariff_schedule",
                to="core.modeldepots",
            ),
        ),
        migrations.CreateModel(
            name="TariffList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=1, max_digits=10, verbose_name="Вес в кг."
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariff",
                        to="core.tariffschedule",
                    ),
                ),
            ],
        ),
    ]
