# Generated by Django 4.2.7 on 2024-09-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_remove_tariffschedule_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptopay",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("paid", "Оплачено"),
                    ("waiting", "Ожидается подтверждение оплаты криптой"),
                    ("unpaid", "Не оплачено"),
                ],
                default="unpaid",
                max_length=10,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
