# Generated by Django 4.2.7 on 2024-09-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_alter_cryptopay_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelpackage",
            name="itemCost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Стоимость за шт"
            ),
        ),
        migrations.AddField(
            model_name="modelpackage",
            name="quantity",
            field=models.IntegerField(
                blank=True, default=1, null=True, verbose_name="Кол-во"
            ),
        ),
        migrations.AlterField(
            model_name="modelbuyerrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создано"),
                    ("confirmed", "Подтверждено"),
                    ("in_progress", "В процессе"),
                    ("bought", "Куплено"),
                    ("sent", "Отправлено"),
                    ("Ожидает оплат", "Ожидает оплаты"),
                    ("Оплачена", "Оплачена"),
                    ("Взята в работу", "Взята в работу"),
                    ("Товар выкуплен", "Товар выкуплен"),
                ],
                default="CREATED",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
