# Generated by Django 4.2.7 on 2024-09-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_confirmemailmodel"),
        ("core", "0065_modelpackage_itemcost_modelpackage_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cryptopay",
            name="package",
        ),
        migrations.AddField(
            model_name="cryptopay",
            name="amount",
            field=models.FloatField(default=0, verbose_name="Сумма оплаты"),
        ),
        migrations.AddField(
            model_name="cryptopay",
            name="wallet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crypto_pay",
                to="user.modelwallet",
            ),
        ),
    ]
