# Generated by Django 4.2.7 on 2024-09-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_remove_cryptopay_package_cryptopay_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartrequest",
            name="itemCost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Стоимость за шт"
            ),
        ),
        migrations.AddField(
            model_name="cartrequest",
            name="quantity",
            field=models.IntegerField(
                blank=True, default=1, null=True, verbose_name="Кол-во"
            ),
        ),
    ]
