# Generated by Django 4.1.10 on 2023-09-22 10:30

import category.imggenerate
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='ModelCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameKg', models.CharField(max_length=100, verbose_name='Мамлекет')),
                ('nameEn', models.CharField(max_length=100, verbose_name='Country')),
                ('nameRu', models.CharField(max_length=100, verbose_name='Страна')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=category.imggenerate.all_image_file_path, verbose_name='Флаг')),
                ('code', models.TextField(blank=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='ModelNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('text', models.TextField(verbose_name='Текст')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='Ссылка на фото')),
                ('read', models.BooleanField(default=False, verbose_name='Статус чтения')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='ModelPackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameKg', models.CharField(max_length=100, verbose_name='Пакеттин аталышы')),
                ('nameEn', models.CharField(max_length=100, verbose_name='Package name')),
                ('nameRu', models.CharField(max_length=100, verbose_name='Название пакета')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=category.imggenerate.all_image_file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Тип посылки',
                'verbose_name_plural': 'Типы посылок',
            },
        ),
        migrations.CreateModel(
            name='ModelWH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mondayStart', models.CharField(blank=True, max_length=10, verbose_name='Начало понедельник')),
                ('mondayEnd', models.CharField(blank=True, max_length=10, verbose_name='Конец понедельник')),
                ('tuesdayStart', models.CharField(blank=True, max_length=10, null=True, verbose_name='Вторник: начало')),
                ('tuesdayEnd', models.CharField(blank=True, max_length=10, null=True, verbose_name='Вторник: конец')),
                ('wednesdayStart', models.CharField(blank=True, max_length=10, null=True, verbose_name='Среда: начало')),
                ('wednesdayEnd', models.CharField(blank=True, max_length=10, null=True, verbose_name='Среда: конец')),
                ('thursdayStart', models.CharField(blank=True, max_length=10, null=True, verbose_name='Четверг: начало')),
                ('thursdayEnd', models.CharField(blank=True, max_length=10, null=True, verbose_name='Четверг: конец')),
                ('fridayStart', models.CharField(blank=True, max_length=10, null=True, verbose_name='Пятница: начало')),
                ('fridayEnd', models.CharField(blank=True, max_length=10, null=True, verbose_name='Пятница: конец')),
                ('satStart', models.CharField(blank=True, max_length=10, null=True, verbose_name='Суббота: начало')),
                ('satEnd', models.CharField(blank=True, max_length=10, null=True, verbose_name='Суббота: конец')),
                ('sundayStart', models.CharField(blank=True, max_length=10, null=True, verbose_name='Воскресенье: начало')),
                ('sundayEnd', models.CharField(blank=True, max_length=10, null=True, verbose_name='Воскресенье: конец')),
            ],
            options={
                'verbose_name': 'Робачие часы',
                'verbose_name_plural': 'Робачие часы',
            },
        ),
        migrations.CreateModel(
            name='ModelCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameKg', models.CharField(max_length=100, verbose_name='Шаар')),
                ('nameEn', models.CharField(max_length=100, verbose_name='City')),
                ('nameRu', models.CharField(max_length=100, verbose_name='Город')),
                ('code', models.TextField(blank=True, verbose_name='Код')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.modelcountry', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
