# Generated by Django 4.1.10 on 2023-10-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_modeltariff_modelcosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100, verbose_name='Валюта')),
                ('oneGBIn', models.FloatField(default=0, verbose_name='One G BIn')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
    ]
