# Generated by Django 4.1.10 on 2023-10-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_delete_modeladdress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('icon', models.ImageField(upload_to='uploads/', verbose_name='Иконка')),
                ('link', models.TextField(blank=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Веб сайт',
                'verbose_name_plural': 'Веб сайты',
            },
        ),
    ]
