# Generated by Django 4.1.10 on 2023-10-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_modelwebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcurrency',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Иконка'),
        ),
    ]
