# Generated by Django 4.1.10 on 2023-10-26 05:29

import category.imggenerate
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_modelcurrency_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEn', models.CharField(max_length=200, null=True, verbose_name='Название на английском')),
                ('nameRus', models.CharField(max_length=200, null=True, verbose_name='Название на русском')),
                ('nameKg', models.CharField(max_length=200, null=True, verbose_name='Название на кыргызком')),
                ('isoptovik', models.BooleanField(default=False, verbose_name='Оптовик?')),
                ('priority', models.FloatField(default=0, verbose_name='Приоритет')),
                ('icon', models.ImageField(null=True, upload_to=category.imggenerate.all_image_file_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEn', models.CharField(max_length=200, null=True, verbose_name='Название на английском')),
                ('nameRus', models.CharField(max_length=200, null=True, verbose_name='Название на русском')),
                ('nameKg', models.CharField(max_length=200, null=True, verbose_name='Название на кыргызком')),
                ('icon', models.ImageField(null=True, upload_to=category.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Категория магазина',
                'verbose_name_plural': 'Категории магазинов',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEn', models.CharField(max_length=200, null=True, verbose_name='Название на английском')),
                ('nameRus', models.CharField(max_length=200, null=True, verbose_name='Название на русском')),
                ('nameKg', models.CharField(max_length=200, null=True, verbose_name='Название на кыргызком')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Субкатегория',
                'verbose_name_plural': 'Субгатегории',
                'ordering': ('id',),
            },
        ),
    ]
