# Generated by Django 4.1.10 on 2023-11-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_modelcountry_phonecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='ModelFranchiseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Телефон номер')),
            ],
            options={
                'verbose_name': 'Франшиза',
                'verbose_name_plural': 'Франшизы',
            },
        ),
        migrations.CreateModel(
            name='ModelGbBusinessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Телефон номер')),
                ('info', models.TextField(blank=True, verbose_name='Информация')),
                ('file', models.TextField(blank=True, verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Бизнес-запрос модель Gb',
                'verbose_name_plural': 'Бизнес-запрос модели Gb',
            },
        ),
    ]
