# Generated by Django 4.1.10 on 2023-11-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_modelfile_modelfranchiserequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfranchiserequest',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
        migrations.AddField(
            model_name='modelgbbusinessrequest',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
    ]
