# Generated by Django 4.1.10 on 2023-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_modelfranchiserequest_archive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameRu', models.CharField(max_length=100, verbose_name='Название')),
                ('nameEn', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('nameKg', models.CharField(blank=True, max_length=100, verbose_name='Аталышы')),
                ('icon', models.TextField(blank=True, verbose_name='Иконка')),
                ('infoRu', models.TextField(blank=True, verbose_name='Информация')),
                ('infoEn', models.TextField(blank=True, verbose_name='Information')),
                ('infoKg', models.TextField(blank=True, verbose_name='Маалымат')),
                ('cost', models.FloatField(default=0, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Экстра сервис',
                'verbose_name_plural': 'Экстра сервисы',
            },
        ),
    ]
