# Generated by Django 4.1.10 on 2023-12-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontact',
            name='messangers',
            field=models.TextField(blank=True, verbose_name='Ссылка'),
        ),
    ]
