# Generated by Django 4.1.10 on 2024-01-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_alter_modelcontact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200, verbose_name='Цвет')),
                ('image', models.TextField(blank=True, verbose_name='Рисунок')),
                ('nameRu', models.CharField(max_length=100, verbose_name='Название')),
                ('nameKg', models.CharField(blank=True, max_length=100, verbose_name='Аталышы')),
                ('nameEn', models.CharField(blank=True, max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='ModelMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.FloatField(default=1, verbose_name='ОЗУ')),
                ('storage', models.FloatField(default=1, verbose_name='Объем памяти')),
                ('addCost', models.FloatField(default=0, verbose_name='Add cost')),
            ],
            options={
                'verbose_name': 'Память',
                'verbose_name_plural': 'Память',
            },
        ),
    ]
