# Generated by Django 4.1.10 on 2024-02-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_modelcolor_modelmemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCurrencyFromUsd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.FloatField(default=0, verbose_name='Сом')),
                ('rub', models.FloatField(default=0, verbose_name='Рубль')),
                ('euro', models.FloatField(default=0, verbose_name='Евро')),
                ('tenge', models.FloatField(default=0, verbose_name='Тенге')),
                ('sum', models.FloatField(default=0, verbose_name='Сум')),
                ('yuan', models.FloatField(default=0, verbose_name='Юань')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курс валют',
            },
        ),
    ]
