# Generated by Django 4.1.13 on 2024-08-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0019_modelcurrencyfromusd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonal', models.FloatField(default=0, null=True, verbose_name='Диагональ')),
                ('matrix_type', models.TextField(max_length=100, null=True, verbose_name='Тип матрицы')),
                ('resolution', models.TextField(max_length=100, null=True, verbose_name='Разрешение')),
                ('frame_frequency', models.TextField(max_length=100, null=True, verbose_name='Частота кадров')),
                ('screen', models.FloatField(default=0, null=True, verbose_name='Screen')),
            ],
            options={
                'verbose_name': 'Монитор',
                'verbose_name_plural': 'Монитор',
            },
        ),
        migrations.AlterField(
            model_name='modelmemory',
            name='ram',
            field=models.TextField(max_length=100, verbose_name='ОЗУ'),
        ),
        migrations.AlterField(
            model_name='modelmemory',
            name='storage',
            field=models.TextField(max_length=100, verbose_name='Объем памяти'),
        ),
    ]
