# Generated by Django 4.1.13 on 2024-08-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0020_modelmatrix_alter_modelmemory_ram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelmemory',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='modelmemory',
            name='storage',
        ),
        migrations.AlterField(
            model_name='modelmemory',
            name='addCost',
            field=models.FloatField(default=0, verbose_name='Дополнительная стоимость'),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.TextField(max_length=100, verbose_name='Объем памяти')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='category.modelmemory')),
            ],
            options={
                'verbose_name': 'Объем памяти',
                'verbose_name_plural': 'Объем памяти',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.TextField(max_length=100, verbose_name='ОЗУ')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram', to='category.modelmemory')),
            ],
            options={
                'verbose_name': 'ОЗУ',
                'verbose_name_plural': 'ОЗУ',
            },
        ),
    ]
