# Generated by Django 4.1.13 on 2024-08-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0021_remove_modelmemory_ram_remove_modelmemory_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='memory',
        ),
        migrations.AddField(
            model_name='modelmemory',
            name='ram',
            field=models.TextField(max_length=100, null=True, verbose_name='ОЗУ'),
        ),
        migrations.AddField(
            model_name='modelmemory',
            name='storage',
            field=models.TextField(max_length=100, null=True, verbose_name='Объем памяти'),
        ),
        migrations.AlterField(
            model_name='modelmemory',
            name='addCost',
            field=models.FloatField(default=0, null=True, verbose_name='Add cost'),
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
