# Generated by Django 4.1.13 on 2024-08-22 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0022_remove_storage_memory_modelmemory_ram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelmemory',
            options={'verbose_name': 'Комплектация', 'verbose_name_plural': 'Комплектация'},
        ),
        migrations.CreateModel(
            name='ModelCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=100, verbose_name='CPU')),
                ('gpu', models.CharField(max_length=100, verbose_name='GPU')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cores', to='category.modelmemory')),
            ],
            options={
                'verbose_name': 'Ядро',
                'verbose_name_plural': 'Ядра',
            },
        ),
    ]
