# Generated by Django 4.1.13 on 2024-08-22 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0023_alter_modelmemory_options_modelcore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcore',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cores', to='category.modelmemory'),
        ),
    ]
