# Generated by Django 4.1.13 on 2024-09-02 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_confirmemailmodel"),
        ("category", "0024_alter_modelcore_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelnotification",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="user.client",
            ),
        ),
    ]
