# Generated by Django 4.1.10 on 2023-10-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_modeladdress'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='category.modeladdress', verbose_name='Адреса'),
        ),
    ]
