# Generated by Django 4.1.10 on 2023-10-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_modelwebsite'),
        ('user', '0003_remove_client_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeruser',
            name='countries',
            field=models.ManyToManyField(blank=True, to='category.modelcountry', verbose_name='Страны'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='websites',
            field=models.ManyToManyField(blank=True, to='category.modelwebsite', verbose_name='Веб сайты'),
        ),
    ]
