# Generated by Django 4.1.10 on 2023-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_user_type_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isVerified',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_back',
            field=models.TextField(blank=True, verbose_name='Обратная сторона паспорта'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_front',
            field=models.TextField(blank=True, verbose_name='Лицевая сторона паспорта'),
        ),
    ]
