# Generated by Django 4.1.10 on 2023-11-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_client_isverified_client_passport_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
