# Generated by Django 4.1.10 on 2023-11-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_buyeruser_passport_back_buyeruser_passport_front_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelShopUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRegistered', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент магазина',
                'verbose_name_plural': 'Клиенты магазина',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Клиент'), ('admin', 'Админ'), ('buyer', 'Покупатель'), ('depot_user', 'Склад'), ('support_user', 'Поддержка'), ('store', 'Магазин'), ('shop_user', 'Клиент магазина')], default='client', max_length=30, verbose_name='Тип пользователя'),
        ),
    ]
