# Generated by Django 4.1.10 on 2023-12-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_modelshopuser_id_modelshopuser_user_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='INN'),
        ),
    ]
