# Generated by Django 4.1.10 on 2023-12-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_client_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Код для сброса пароля'),
        ),
    ]
