# Generated by Django 4.1.10 on 2023-12-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_modelcontact_messangers'),
        ('user', '0012_user_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='about_yourself',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='commission',
            field=models.TextField(blank=True, verbose_name='Размер комиссии'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.modelcontact', verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_country', to='category.modelcountry', verbose_name='Страна проживания'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='paymentType',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='redemption_speed',
            field=models.CharField(default=1, max_length=200, verbose_name='Скорость выкупа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='search_product',
            field=models.TextField(blank=True, verbose_name='Поиск товаров'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='shop_countries',
            field=models.ManyToManyField(blank=True, related_name='shop_countries', to='category.modelcountry'),
        ),
    ]
