# Generated by Django 4.1.10 on 2023-12-15 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_modelcontact_messangers'),
        ('user', '0013_modelbecomebuyer_about_yourself_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeruser',
            name='commission',
            field=models.TextField(blank=True, verbose_name='Размер комиссии'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.modelcontact', verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='paymentType',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='search_product',
            field=models.TextField(blank=True, verbose_name='Поиск товаров'),
        ),
    ]
