# Generated by Django 4.1.10 on 2024-01-03 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_alter_modelcontact_email'),
        ('user', '0014_buyeruser_commission_buyeruser_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeruser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_foreignKey', to='category.modelcountry', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='face',
            field=models.TextField(blank=True, verbose_name='Фейсбук'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='faceLink',
            field=models.TextField(blank=True, verbose_name='Ссылка на фейсбук'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='insta',
            field=models.TextField(blank=True, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='instaLink',
            field=models.TextField(blank=True, verbose_name='Ссылка на инстаграм'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='redemption_speed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Скорость погашения'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='tg',
            field=models.TextField(blank=True, verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='tgLink',
            field=models.TextField(blank=True, verbose_name='Ссылка на телеграм'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='whatsApp',
            field=models.TextField(blank=True, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='whatsAppLink',
            field=models.TextField(blank=True, verbose_name='Ссылка на WhatsApp'),
        ),
        migrations.AlterField(
            model_name='buyeruser',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='countries', to='category.modelcountry', verbose_name='Страны'),
        ),
    ]
