# Generated by Django 4.1.10 on 2024-01-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_buyeruser_country_buyeruser_email_buyeruser_face_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='face',
            field=models.TextField(blank=True, verbose_name='Фейсбук'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='faceLink',
            field=models.TextField(blank=True, verbose_name='Ссылка на фейсбук'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='insta',
            field=models.TextField(blank=True, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='instaLink',
            field=models.TextField(blank=True, verbose_name='Ссылка на инстаграм'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='tg',
            field=models.TextField(blank=True, verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='tgLink',
            field=models.TextField(blank=True, verbose_name='Ссылка на телеграм'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='whatsApp',
            field=models.TextField(blank=True, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='modelbecomebuyer',
            name='whatsAppLink',
            field=models.TextField(blank=True, verbose_name='Ссылка на WhatsApp'),
        ),
        migrations.AlterField(
            model_name='modelbecomebuyer',
            name='redemption_speed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Скорость погашения'),
        ),
    ]
