# Generated by Django 4.1.10 on 2024-01-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_modelbecomebuyer_email_modelbecomebuyer_face_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isVip',
            field=models.BooleanField(default=False, verbose_name='Статус VIP'),
        ),
    ]
