# Generated by Django 4.1.10 on 2024-01-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_client_isvip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmEmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, verbose_name='Электронная почта')),
                ('confirm_code', models.CharField(blank=True, max_length=6, verbose_name='Код для подтверждения электронной почты')),
            ],
            options={
                'verbose_name': 'Подтвержденная почта',
                'verbose_name_plural': 'Подтвержденные почты',
            },
        ),
    ]
